{{- if .Values.config.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bee-slack.configSecretName" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.config.fileName }}: |
    {{- dict "appToken" .Values.config.appToken "botToken" .Values.config.botToken "nats" .Values.config.nats "routes" .Values.config.routes | toPrettyJson | nindent 4 }}
{{- end }}
